"""Dream Cycle data models.

Dataclasses for the four-agent pipeline: Explorer → Thinker → Consensus Panel.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class DreamCycleResult:
    """Result of a complete dream cycle run."""

    run_id: str
    run_type: str  # scheduled, post_learn, session_start, user_triggered
    started_at: datetime
    completed_at: datetime
    candidates_generated: int
    candidates_accepted: int
    candidates_rejected: int
    digest_path: str | None = None  # path to markdown digest file
    aborted_early: bool = False  # True if circuit breaker fired (empty slices)


@dataclass
class MemorySlice:
    """A curated set of memories assembled by the Explorer using a named strategy."""

    name: str  # e.g., "Cross-project database decisions"
    strategy: str  # e.g., "cross_project_collision"
    memory_ids: list[str] = field(default_factory=list)  # UUIDs of included memories
    memory_titles: list[str] = field(default_factory=list)  # Titles for logging/digest
    hypothesis: str = ""  # 1-2 sentence hypothesis for the Thinker


@dataclass
class CandidateInsight:
    """A candidate insight generated by the Thinker for evaluation."""

    title: str
    type: str  # insight, connection, question, synthesis
    operation: str  # CREATE, UPDATE, SUPERSEDE
    target_memory_id: str | None = None  # for UPDATE/SUPERSEDE
    supersedes_reason: str | None = None
    schema_operation: str = "assimilation"  # assimilation, accommodation
    schema_note: str = ""
    confidence: str = "medium"  # high, medium, low
    confidence_reasoning: str = ""
    content: str = ""  # Full insight text with depth framework
    source_memories: list[str] = field(default_factory=list)  # UUIDs
    relationships: list[dict] = field(default_factory=list)  # [{target_id, relation_type, note}]
    strategy_that_found_it: str = ""


@dataclass
class EvaluatorVerdict:
    """A binary verdict from a single evaluator on the Consensus Panel."""

    role: str  # skeptic, advocate, epistemologist, methodologist
    verdict: str  # ACCEPT, REJECT
    reasoning: str = ""  # Full reasoning text
